### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by lxea** [Reydw/Fbx-Converter-GUI#1]
Hey the download is broke, the download is one byte and fails to extract. Thanks

**Comment by ilinaraducristian** [comment]
Thx for feedback ill fix it asap.

**Comment by ilinaraducristian** [comment]
Hi! Now it should be ok. I hope you'll be satisfied with my product.

2014-12-08 6:08 GMT+02:00 Reydw Rey oraclle98@gmail.com:

> Thx for feedback ill fix it asap.
